DROP TABLE IF EXISTS motorcycles;
DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS cities;

CREATE TABLE motorcycles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  make TEXT,
  model TEXT,
  horsepower INTEGER NOT NULL
);

CREATE TABLE pokemon (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  type_1 TEXT,
  type_2 TEXT,
  attack INTEGER NOT NULL
);

CREATE TABLE cats (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  type TEXT,  
  lives INTEGER,
  is_sidekick BOOLEAN
);

CREATE TABLE people (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  age INTEGER,  
  born_in TEXT
);

CREATE TABLE cities (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  country TEXT,  
  has_beach BOOLEAN
);

